export class User {
    constructor(
        public registroid?: number,
        public tipo?: string,
        public email?: string,
        public password?: string,
        public notificacion?: number,
        public razSocialEmp?: string,
        public paisEmp?: string,
        public provinciaEmp?: string,
        public direccionEmp?: string,
        public tipoDocEmp?: string,
        public giroNegEmp?: string,
        public departamentoEmp?: string,
        public distritoEmp?: string,
        public nroDocEmp?: string,
        public nombreRep?: string,
        public apellidosRep?: string,
        public tipoDocRep?: string,
        public nroDocRep?: string,
        public emailRep?: string,
        public telefRep?: string,
        public nombrePerN?: string,
        public apellidosPerN?: string,
        public tipoDocPerN?: string,
        public nroDocPerN?: string,
        public telfPerN?: string,
        public paisPerN?: string,
        public departamentoPerN?: string,
        public provinciaPerN?: string,
        public distritoPerN?: string,
        public direccionPerN?: string
    ) {  }
}
